version: '3'
services:
  haproxy:
    build: .
    volumes:
      - ./haproxy.tmpl:/app/haproxy.tmpl
      - /var/run/docker.sock:/tmp/docker.sock
    ports:
      - 80:80
      - 443:443
    network_mode: bridge